### Artificial Neural Network

### Importing the Libraries

In [33]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [34]:
tf.__version__

'2.16.1'

### Part 1 - Data Preprocessing

### Importing the Dataset

In [35]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [36]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [37]:
print(y)

[1 0 1 ... 1 1 0]


### Enconding Categorical Data

##### Label Enconding the "Gender" Column

In [38]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [39]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


#### One Hot Encoding the Geography Column

In [40]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [41]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the Dataset into the Training set and Test set

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [43]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN 

In [44]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [45]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [46]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the Output Layer

In [47]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [48]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [49]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100


250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 546us/step - accuracy: 0.5983 - loss: 0.6953
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 494us/step - accuracy: 0.7978 - loss: 0.5033
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 502us/step - accuracy: 0.7882 - loss: 0.4640
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - accuracy: 0.8003 - loss: 0.4286
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 510us/step - accuracy: 0.8140 - loss: 0.4062
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 462us/step - accuracy: 0.8254 - loss: 0.3968
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - accuracy: 0.8280 - loss: 0.3901
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.8308 - loss: 0.3866
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - accuracy: 0.8383 - loss: 0.3732
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - accuracy: 0.8428 - loss: 0.3697
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 462us/step - accuracy: 0.8468 - loss: 0.3667
Epoch 12/100
250/250 ━━━━━━━━━━

## Making the predictioins and evaluating the Model


### Predicting the Result of a single observation

### Predicting the Test set results

In [50]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
